- hosts: ambari-agents
  user: root
  vars:
    hdp_ambari_repo: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.5.0.3/ambari.repo
    ambarihostname: management.master
  tasks:

    - name: Add ambari repo
      get_url:
        url: "{{hdp_ambari_repo}}"
        dest: /etc/yum.repos.d/ambari.repo

    - name: Install Ambari Agent
      yum:
        pkg: ambari-agent
        state: installed
 
    - name: Configure Ambari agent to register at Ambari server
      lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini create=no state=present regexp='hostname=.*' line='hostname={{ ambarihostname }}'

    - name: start ambari-agent
      service: name=ambari-agent state=started enabled=yes
