- hosts: hdp-machines
  user: root
  vars:
    java_download_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
    java_download_folder: /opt
    java_name: "{{java_download_folder}}/jdk1.8.0_131"
    java_archive: "{{java_download_folder}}/jdk-8u131-linux-x64.tar.gz"

  tasks:

    - name: Disable yum fastestmirror
      lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf state=present create=yes regexp='enabled=.*' line='enabled=0'

    - name: Install curl
      yum:
        pkg: curl
        state: installed

    - name: Install unzip
      yum:
        pkg: unzip
        state: installed

    - name: Install wget
      yum:
        pkg: wget
        state: installed

    - name: permanently set ulimit - soft
      lineinfile: dest=/etc/security/limits.conf state=present create=yes regexp='\*    soft    nofile *' line='*    soft    nofile 12000'

    - name: permanently set ulimit - hard
      lineinfile: dest=/etc/security/limits.conf state=present create=yes regexp='\*    hard    nofile *' line='*    hard    nofile 12000'

    - name: Install NTP
      yum:
        pkg: ntp
        state: installed

    - name: Enable and start ntp
      service: name=ntpd state=started enabled=yes

    - name: Configure iptables
      service: name=firewalld state=stopped enabled=no

    - name: Disable SELinux
      lineinfile: dest=/etc/selinux/config state=present create=yes regexp='SELINUX=.*' line='SELINUX=disabled'

    - name: umask
      lineinfile: dest=/etc/profile state=present create=yes line='umask 0022'

    - name: Register /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }}    {{ hostvars[item].inventory_hostname }}"
        state: present
      with_items: "{{ groups.all }}"